### ISSUE TITLE
add a confirmation option to eliminate taskid and taskgroupid typos

### ISSUE THREAD

**Issue by lundjordan** [taskcluster/taskcluster-cli#188]
a few times during releases, releaseduty have accidently rerun the wrong task which has caused trouble with chainoftrust and dependant subsequent tasks in the release graph.

It would be great to have an option (configurable to be the default behaviour) where you had to confirm when you run mutable commands. e.g. rerun, cancel, etc. and the cli provides you with more meaningful task description in the confirmation

This could also have an override option (e.g. --force) in cases you are confident or want to script a bunch of calls.

While this may be resolved with a wrapper script around taskcluster-cli, it probably makes sense to bake it directly inside taskcluster-cli

**Comment by lundjordan** [comment]
context: https://trello.com/c/xUnoy6k1/33-taskcluster-cli-should-have-a-confirm-option-perhaps-wrapper

**Comment by lundjordan** [comment]
@srfraser could help mentor on the use case and possibly implementation. Core authors from Taskcluster would be good resources too

**Comment by lundjordan** [comment]
@mutterroland seem like something you would be interested in trying? It is a good-first-bug I think. taskcluster-cli is written in Go which is pretty readable and friendly. However, like I said in the description, you could always write a wrapper in python as a standalone script if you get stuck. That wrapper could live in releasewarrior instead: https://github.com/mozilla-releng/releasewarrior-2.0/tree/master/scripts

**Comment by escapewindow** [comment]
For `rerun`, we specifically want to check for status in `['failed', 'exception']` and require `--force` to rerun completed tasks.

**Comment by djmitche** [comment]
This sounds like a cool idea!

In designing this, keep in mind that taskcluster-cli is a general-purpose client and we want to make sure that it "makes sense" to a user arriving from outside Releng or outside Mozilla.

TC-cli has a class of commands (basically everything except `taskcluster api`) that perform common TC operations in a more friendly fashion than just calling an API method (`taskcluster api` is bare API method calls, and is autogenerated).  The proposed functionality should apply consistently to all of those common-operations commands.

Options I can see:
 * `--noop` that just prints the operation to perform (and adjust some operations to print extra information, e.g., rerun would always print the task name and run statuses)
 * `--confirm` that prompts for user input with `[y/N]` before performing any changes
 * a `requireConfirmation` config setting which, if set, runs every operation in noop mode unless `--confirm` is given on the command line
 * more?

We also need to be careful not to break compatibility.  In particular, a tool that is in use for scripting which suddenly starts waiting for the user to type `y` ends up hanging and can cause a lot of pain for other users.  So that shouldn't be the default!  It could be something you can configure though.

I think that requiring `--force` for a rerun of a non-failed task is a good idea, but a different project (and I seem to recall a bug or issue for it already, but if not -- a good one to open).

**Comment by djmitche** [comment]
Yes, I was thinking task name rather than (multiline) description, but that's the idea.

Let's leave rerun to another bug.  It sounds like that could get complicated :)

**Comment by escapewindow** [comment]
`rerun --force` for completed tasks is the only piece that I consider urgent here -- it's the part that's bitten us twice on releaseduty recently.

**Comment by djmitche** [comment]
OK, I created #189 for that :)

**Comment by mutterroland** [comment]
Have been talking with @srfraser about that. With him as a mentor, we've started working on it .

**Comment by mutterroland** [comment]
Opened a pull request for noop flag: https://github.com/taskcluster/taskcluster-cli/pull/196

**Comment by djmitche** [comment]
@mutterroland this is done now, right?

**Comment by mutterroland** [comment]
@djmitche I have to change the code a little bit to make it ready for the merge. Will try to finish it on today's shift :)

**Comment by mutterroland** [comment]
@djmitche  I've done some changes to the pull request
